male(PrincePhillip).
male(PrinceCharles).
male(CaptainMarkPhillips).
male(TimothyLaurence).
male(PrinceAndrew).
male(PrinceEdward).
male(PrinceWilliam).
male(PrinceHarry).
male(PerterPhillips).
male(MikeTindall).
male(PrinceGeorge).
male(JamesViscountSevern).
male(a).


female(QueenElizabethII).
female(PrincessDiana).
female(CamillaParkerBowles).
female(PrincessAnne).
female(SarahFerguson).
female(SophieRhys-jones).
female(KateMiddletion).
female(AutumnKelly).
female(ZaraPhillips).
female(PrincessBeatrice).
female(PrincessEugenie).
female(PrincessCharlotte).
female(SavannahPhillips).
female(IslaPhillips).
female(LadyLouiseMountbattenWindsor).